### ISSUE TITLE
Navbar Homepage (detta HP): aggiungere pulsanti "Dona" e "Dove dormire"

### ISSUE THREAD

**Issue by nelsonmau** [SiciliaHub/ods16#10]
in index.html (homepage, o HP) aggiungere due pulsanti:
- **Dona** : linka alla pagina `dona.html`
- **Dove dormire** : linka alla pagina `accomodation.html`

vai peppino! :-)

**Comment by giuragu** [comment]
@nelsonmau ok vado e torno :)
