### ISSUE TITLE
Missing URL to http://www.openpolis.it/

### ISSUE THREAD

**Issue by patperu** [SiciliaHub/ods16#5]
Ciao Andrea,
the last `href` attribute in https://github.com/SiciliaHub/ods16/blob/gh-pages/index.html#L269 is empty. Should be `http://www.openpolis.it/`

**Comment by nelsonmau** [comment]
You are my lucky star!
`Press Play To Continue`
 https://www.youtube.com/watch?v=bi1cp7nNKpA
