### ISSUE TITLE
condividere grafica banner #ODS16

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/ods16#7]
@nelsonmau inserisci in formato editabile la grafica (il file) che hai costruito per #ods16 e magari la metti in questa cartella https://github.com/SiciliaHub/ods16/tree/master/comunicazione?

Se hai usato font "speciali", inseriscili pure sul repo.

grazie

**Comment by nelsonmau** [comment]
done! https://github.com/SiciliaHub/ods16/tree/master/comunicazione
