### ISSUE TITLE
Completare pagina accomodation

### ISSUE THREAD

**Issue by giuragu** [SiciliaHub/ods16#9]
Completare la pagina accomodation con un messaggio iniziale e aggiungere di volta in volta eventuali e ulteriori possibili alloggi.
Si prevede anche l'inserimento di una mappa @nelsonmau

**Comment by nelsonmau** [comment]
Questi i luoghi suggeriti da francesco micali

---

http://www.messina41.it/ vicininissimo il luogo dell'evento
http://www.emmemessina.it/  in centro ma non vicinissimo al luogo dell'evento e forse possiamo strappare dei coupon
http://www.metropolisbb.com/dovesiamo.html
http://www.portadellasicilia.com/bed-and-breakfast-messina/ vicino il luogo dell'evento
http://www.operabnb.com/dove_siamo.html vicino il luogo dell'evento
http://www.cairolibandb.it/ in centro ma non vicinissimo al luogo dell'evento

**Comment by nelsonmau** [comment]
ottimo tutto, ho solo sistemato il tag **title** che si trova all'interno del blocco 
**head**
di una pagina.

---

`<title>Dove dormire » #ODS16 | OpenDataSicilia Summer Edition / Messina, 2-3-4 Settembre 2016 </title>`

---

quello che c'è scritto qui compare nel titolo della tab del browser (era rimasto 'donazioni', ho messo 'dove dormire'

(scrivo male perché non mi funzia il markdown e sono di fretta... )

**Comment by nelsonmau** [comment]
@giuragu: il mitico @picomiles si candida per fare la mappa dei B&B, passa a lui la palla o fate insieme? ciao! spicciatevi! :D 

e grazie :kissing:

**Comment by picomiles** [comment]
@giuragu non so se posso essere d'aiuto, in caso, ben volentieri

Il 26/lug/2016 13:17, "Andrea Nelson Mauro" notifications@github.com ha
scritto:

@giuragu https://github.com/giuragu: il mitico @picomiles
https://github.com/picomiles si candida per fare la mappa dei B&B, passa
a lui la palla o fate insieme? ciao! spicciatevi! :D

e grazie 😗

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/SiciliaHub/ods16/issues/9#issuecomment-235239417, or mute
the thread

**Comment by picomiles** [comment]
@giuragu non so se posso essere d'aiuto, in caso, ben volentieri

Il 26/lug/2016 13:17, "Andrea Nelson Mauro" notifications@github.com ha
scritto:

**Comment by giuragu** [comment]
@picomiles Ciao Nino! ho predisposto la paginetta  [Dove dormire](http://ods16.opendatasicilia.it/accomodation.html). Potremmo inserire la mappa in basso aggiungendo in più i luoghi dell'evento. Che ne pensi? Inoltre....procediamo con UMAP?

**Comment by giuragu** [comment]
@nelsonmau Con il mitico @picomiles abbiamo messo su una prima bozza della mappa già on line alla pagina [Dove dormire](http://ods16.opendatasicilia.it/accomodation.html). A breve Nino inserirà anche i marker inerenti il luogo dell'evento...

**Comment by picomiles** [comment]
la mappa dovrebbe essere completa, se avete altri suggerimenti dite pure,
basta però ca finiti mi vi bagnati u pani cu sta storia du miticu...

N.

Il giorno 26 luglio 2016 17:49, Giuseppe Ragusa notifications@github.com
ha scritto:

**Comment by aborruso** [comment]
mitici, grazie ragazzi
